# NumPy
short for Numerical Python, is one of the most important foundational packages
for numerical computing in Python. Most computational packages providing
scientific functionality use NumPy’s array objects as the lingua franca for data
exchange.
Here are some of the things you’ll find in NumPy:
- ndarray, an efficient multidimensional array providing fast array-oriented arithmetic
operations and flexible broadcasting capabilities.
- Mathematical functions for fast operations on entire arrays of data without having
to write loops.
- Tools for reading/writing array data to disk and working with memory-mapped
files.
- Linear algebra, random number generation, and Fourier transform capabilities.
- A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

# NumPy Practice

###### import numpy as np 

* Numpy is imported
* aliased as np

In [2]:
import numpy as np

# 1.  Create a Numpy array

NumPy arrays are homogenous: all elements should be of same datatypes.
NumPy array can be created using following methods:

1. from lists:
```` python
List = [[1,2,4,5], [6,7,5,7,8]]
nArray = np.array(List)
````

In [3]:
List = [[1,2,4,5], [6,7,5,7,8]]
nArray = np.array(List)
nArray

array([list([1, 2, 4, 5]), list([6, 7, 5, 7, 8])], dtype=object)

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

# 2. Zeros and Ones


``np.zeros`` creates an array of zeros of given dimension
<br>
``np.ones`` creates an array of one of given dimension.

these fucntions takes a second parameter specifying the datatype of array

In [5]:
ZeroArray = np.zeros(10)
ZeroArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
OneArray = np.ones(10)
OneArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


# 3. Details of functions for NumPy array creation

|Function|Description|
|:-------|:----------|
|array| Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtypeor explicitly specifying a dtype; copies the input data by default
|asarray| Convert input to ndarray, but do not copy if the input is already an ndarray
|arange| Like the built-in range but returns an ndarray instead of a list
|ones,ones_like|Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype
|zeros, zeros_like|Like ones and ones_like but producing arrays of 0s instead
|empty, empty_like|Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
|full, full_like|Produce an array of the given shape and dtype with all values set to the indicated “fill value” full_like takes another array and produces a filled array of the same shape and dtype
|eye|identity Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)
|linspace|Return evenly spaced numbers over a specified interval.

In [7]:
#following line create a list of zeros with dtype of int16 
ZeroArray1 = np.zeros(10)
ZeroArray1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#following line create a list of zeros with dtype of int8
onesArray1 = np.ones(10)
onesArray1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
#following line create a list of zeros with dtype of int8
onesArray1 = np.array([1,2,3,4,5,4])
onesArray1

array([1, 2, 3, 4, 5, 4])

In [10]:
# creates an array or 5 elements with a garbage values.
np.empty(5)

array([1.69119330e-306, 1.29061821e-306, 4.45061456e-308, 9.34604358e-307,
       3.44897822e-307])

In [11]:
# similar to range() in list, but returns an NumPy Array
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#Return evenly spaced numbers over a specified interval.
# linspace(num1, num2, num=n)
# it will generate n numbers, equally spaced between  num1 and num2 

np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [13]:
np.linspace?

# 4. Data Type of NumPy Array

the datatype can be assigned using datatype parameter. By default the datatype is float (64-bit float)<br>
other data types are
    
##### Numpy Data Type:

|Data Type|Type Code|Description|
|:--------|:--------|:----------|
|int8, uint8|i1, u1|Signed and unsigned 8-bit (1 byte) integer types|
|int16, uint16| i2, u2| Signed and unsigned 16-bit integer types|
|int32, uint32| i4, u4| Signed and unsigned 32-bit integer types|
|int64, uint64| i8, u8| Signed and unsigned 64-bit integer types|
|float16| f2| Half-precision floating point|
|float32| f4 or f| Standard single-precision floating point; compatible with C float|
|float64| f8 or d| Standard double-precision floating point; compatible with C double and Python float object|
|float128| f16 or g| Extended-precision floating point|
|complex64, complex128, complex256 |c8, c16, c32 |Complex numbers represented by two 32, 64, or 128 floats, respectively|
|bool| ?|Boolean type storing True and False values|
|object| O| Python object type; a value can be any Python object|
|string_ |S| |Fixed-length ASCII string type (1 byte per character); for example, to create astring dtype with length 10, use 'S10'|
|unicode_| U| Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')|
    
    


In [14]:
unit16Array = np.ones(10,dtype= np.int8)
print(f"data type of single element is: {type(unit16Array[1])}")

data type of single element is: <class 'numpy.int8'>


In [15]:
float16Array = np.ones(10,dtype= np.float16)
print(f"data type of single element is: {type(unit16Array[1])}")

data type of single element is: <class 'numpy.int8'>


In [16]:
ArrangeArray = np.arange(4, 11, 2, dtype = np.int64)
print(ArrangeArray)

[ 4  6  8 10]


In [17]:
fromList = np.array([1,2,25,15], dtype = np.uint8)
fromList

array([ 1,  2, 25, 15], dtype=uint8)

In [18]:
np.linspace?

# 5. Type Casting of NumPy Array 

The dtype of NumPy Array can be changes by using np.astype() method. For example

In [19]:
ArraytoCast = np.arange(5,dtype= np.int16)
print(f"Array element data type is {type(ArraytoCast[0])}")

CastedArray = ArraytoCast.astype(np.float16)
print(f"Array element data type is {type(CastedArray[0])}")


Array element data type is <class 'numpy.int16'>
Array element data type is <class 'numpy.float16'>


# 6. Numpy Random Module

Numpy Random module is used to generate a random numbers in NumPy. For Now we will focus on four methods

|Method|Description|
|:-----|:----------|
|rand(d0, d1,...)| uniform distribution of random values of a given shape.|
|randn(d0, d1,...)| return normally distributed random values of given shape |
|randf(d0, d1,...)| return random float numbers in half-open interval 0-1|
|randint(low, high=None, size=None, dtype='l')| return random int numbers between low and high with specified size (a tuple of m ,n ,k)|


In [20]:
np.random.randint?

In [21]:
np.random.rand(5)

array([0.01568365, 0.6994918 , 0.54188819, 0.02268275, 0.78898975])

In [22]:
np.random.randn(5)

array([-0.18076364, -0.33101611, -0.37350659, -0.02851475,  2.09667736])

In [23]:
np.random.ranf(5)

array([0.65248253, 0.03050736, 0.38235179, 0.80040555, 0.13998814])

In [24]:
np.random.randint(2,5,(2,5))

array([[2, 3, 2, 4, 3],
       [4, 4, 3, 3, 3]])

# 7. Dimension of a NumPy Array

Dimension, sometimes also called axis, of NumPy Array can be describes the number of verctors (array) spaces in a NumPy Array. (in simple words number of lists in Numpy Array is the dimension of array)
for example:
 ```` python

A_2D_Array = np.array([[1,2,3],[4,5,6]]) 
````
is a two dimenstion of array

dimenstion of an array can be obtained by using .ndim attribute

# 8. Shape of a NumPy Array

Shape of array is a tuple that contains number of elements in each dimension or axis.
for example a shape of (2,3,4) specifies that there are 2 elements in dimension/axis 1, 3 elements in dimension/axis 2 and 4 elements in dimension/axis 3.

A shape of an array can be get by using .shape attribute.


In [25]:
A_2D_Array = np.array([[1,2,3],[4,5,6]])
A_2D_Array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A_2D_Array.ndim

2

In [27]:
A_2D_Array.shape

(2, 3)

### Initialization with a specific dimension and shape.

A np array can be initialized using a specific dimesnion and shape.

##### Using zeros 


```` python
A3DArrayZeros = np.zeros(2, 3, 5) 
````

In [28]:
np.zeros?

In [29]:

A3DArrayZeros = np.zeros((2, 3, 5))
A3DArrayZeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
A3DArrayZeros.ndim

3

In [31]:
A3DArrayZeros.shape

(2, 3, 5)

##### using ones

```` python
A3DArrayOnes = np.ones((2,3,4), dtype = np.int8)
````

In [32]:
np.random.rand?

In [33]:
A3DArrayOnes = np.ones((2,3,4), dtype = np.int8)
A3DArrayOnes

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

##### using random.rand
##### suing random.randn
##### suing random.ranf

```` python
np.random.rand(d0, d1, ..., dn)
np.random.randn(d0, d1, ..., dn)
np.random.ranf(d0, d1, ..., dn)
````

The random functions rand function, however the dimension and shape is given as separate parameters rather than a in a single parameter in term of tuple.

In [34]:
A3DArrayRand= np.random.rand(2,2,2)
A3DArrayRand

array([[[0.3476837 , 0.41629447],
        [0.04247628, 0.48230548]],

       [[0.6095994 , 0.9828076 ],
        [0.02399692, 0.04582733]]])

In [35]:
A3DArrayRandn= np.random.rand(2,2,2)
A3DArrayRandn

array([[[0.98836898, 0.65839829],
        [0.25287106, 0.50607527]],

       [[0.88647734, 0.7757618 ],
        [0.58108939, 0.05878822]]])

In [36]:
A3DArrayRanf= np.random.rand(2,2,2)
A3DArrayRanf

array([[[0.10775685, 0.26642975],
        [0.33460425, 0.46289714]],

       [[0.67251588, 0.2094188 ],
        [0.80572249, 0.27460469]]])

##### using random.randint

```` python
numpy.random.randint(low, high=None, size=None, dtype='l')	
````

the ranint function takes upper and lower limits, besides that size takes a tuple which defines the dimension and shape of resulting array.


In [37]:
A3DArrayRanInt = np.random.randint(5,10,(2,2,3))
A3DArrayRanInt

array([[[8, 6, 9],
        [9, 9, 6]],

       [[8, 6, 9],
        [8, 5, 9]]])

In order to better understand the dimension and shapes, we can 

# 9. Idexing

index is similar to list in pyhon. Index can be positive or negative. A value can be accessed and changed using indices.

In [38]:
Array1DIndex = np.arange(5)
Array1DIndex[4]

4

In [39]:
Array1DIndex = np.arange(5)
Array1DIndex[-2]

3

### Indexing of Two Dimensional array

In order to obtain a value in 2D array, one needs to give index for each dimension. For our ease we can call element distributed in rows and column in these dimensions. rows goes vertical and column are vertical. in mathematical form it can be said that an element in  i x j matrix a (NumPy Array are just matrices) can be represented as $a_{i+1,j+1}$ and need [row_index][column_index] in order to access single element in python. In order to have a rough visual representation of 2D array see the table below   

|ixj matrix|        |||||
|:--------:|:------:|:------:|:------:|:------:|:------:|
|Column    |        |Column1 |Column2 |Column3 |Column4 |
|Index (j) |        |0       |1       |2       |3       | 
|row       |index(i)|        |        |        |        |
|row1      |0       |0       |1       |2       |3       |
|row2      |1       |4       |5       |6       |7       |
|row3      |2       |8       |9       |10      |11      |
|row4      |3       |12      |13      |14      |15      |
|row5      |4       |16      |17      |18      |19      |


in above 2D array (or matrix) and element can be accessed by using row and column (both dimensions) indices. for example value at indices [3][2] (or $a_{43}$) is 14

In [40]:
Array2DIndex=np.arange(20).reshape(5,4)
Array2DIndex

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
Array2DIndex[3][2]

14

if column index is not given result will be a whole row in single dimension.

In [42]:
Array2DIndex[3]

array([12, 13, 14, 15])

## Indexing 3D Array

Similar to 2D arrays, 3D arrays needs 3 indices in orders in get a single value, if a one indix is missing, matrix is return on given axis will be returned.

In [43]:
Array3DArray = np.arange(24).reshape(2,3,4)
Array3DArray[1][1][3]  # should return 19

19

## Indexing n-Dimensional Array

An n-dimensional array take n number of indices to get a number

# 10. Slicing

Slicing works similar to lists in python and can be done using [start:end:step], where end index is not inclusive
consider for an array named

1. arr[start:end] -> an array between start and end-1 indices
2. arr[:end] -> an array between 0 index and end-1 index
3. arr[start:] -> an array from start index to the last element(inclusive)
4. arry[start:end:step] -> array from start to end-1 index with a step of 2.

for example

In [44]:
SlicingArray = np.arange(24)
SlicingArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
SlicingArray[0:5]

array([0, 1, 2, 3, 4])

In [46]:
SlicingArray[20:]

array([20, 21, 22, 23])

In [47]:
SlicingArray[5:10]

array([5, 6, 7, 8, 9])

In [48]:
SlicingArray[2:10:2]

array([2, 4, 6, 8])

In [49]:
SlicingArray[-5:-1]

array([19, 20, 21, 22])

## Slicing of 2-Dimensional Array

2-dimensional array can be sliced by giving slicing indices for each dimension.
for a two dimensional array the slicing should follow this procedure
suppose 2 dimensions are d1(row), d2(column) the syntax for slicing would be:
```` python
arr[start_d1:end_d1:step_d1, start_d2:end_d2:step_d2]
````

Consider following 2D Arrray


||        |||||
|:--------:|:------:|:------:|:------:|:------:|:------:|
|Column    |        |Column1 |Column2 |Column3 |Column4 |
|Index (j) |        |0       |1       |2       |3       | 
|row       |index(i)|        |        |        |        |
|row1      |0       |0       |1       |2       |3       |
|row2      |1       |4       |5       |6       |7       |
|row3      |2       |8       |9       |10      |11      |
|row4      |3       |12      |13      |14      |15      |
|row5      |4       |16      |17      |18      |19      |

In [50]:
Slicing2DArray = np.arange(20).reshape(5,4)
Slicing2DArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

```` python
Slicing2DArray[1:3,2:4]
````

would give the element between row1 to row2 (row index 3 in exclusive) and column2 to column3. 

In [51]:
Slicing2DArray[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

```` python
Slicing2DArray[:,2:4]
````

would all elements of all rows between column3 and column4

In [52]:
Slicing2DArray[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

```` python
Slicing2DArray[2:4,:]
````

would all elements of all rows between row3 and row4

In [53]:
Slicing2DArray[2:4,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Slicing 3-D Array

Similary for 3D array slicing index for each dimension of axis have to be given and, if a dimensionor axis don't need to be sliced : is kept for that dimension. The syntax for slicing is


```` python
arr[start_d1:end_d1:step_d1, start_d2:end_d2:step_d2,start_d3:end_d3:step_d3]
````

for example:

In [54]:
Slicing3DArray = np.arange(75).reshape(3,5,5)
Slicing3DArray

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [55]:
Slicing3DArray[1:,1:3,2:4]

array([[[32, 33],
        [37, 38]],

       [[57, 58],
        [62, 63]]])

In [56]:
Slicing3DArray[:,1:3,2:4]

array([[[ 7,  8],
        [12, 13]],

       [[32, 33],
        [37, 38]],

       [[57, 58],
        [62, 63]]])

In [57]:
Slicing3DArray[1:,:,2:4]

array([[[27, 28],
        [32, 33],
        [37, 38],
        [42, 43],
        [47, 48]],

       [[52, 53],
        [57, 58],
        [62, 63],
        [67, 68],
        [72, 73]]])

### Slicing n-D Array

In order to slice an n-dimensional array, slicing index of each dimension should be given. the syntax would be 

```` python
arr[start_d1:end_d1:step_d1, start_d2:end_d2:step_d2,start_d3:end_d3:step_d3,...,start_dn:end_dn:step_dn]
````


# 11. Ellipsis in Slicing

Suppose we are using a NumPy array which have a greater number of dimensions,let say 5 dimensions created by following code.

```` python
A_7D_Array = np.arange(216).reshape(3,1,1,1,4)
````
now this array will have 7 dimension with a shape of (3,1,1,1,4). 
<br><br>
our requirement is to slice the 5th axis. For slicing we would need to give : for wach axis in slicing indexing, as shown below:
```` python
A_7D_Array[:,:,:,:,1:2]
````
<br>

rather than using : for each axis which isn't to be sliced. We can use ellipsis `...` instead of all these :, for example an equivalent of the code above is:

```` python
A_7D_Array[...,1:2]
````


In [58]:
A_7D_Array = np.arange(216).reshape(3,3,2,3,4)
#A_7D_Array

In [59]:
A_7D_Array[:,:,:,:,1:2]

array([[[[[  1],
          [  5],
          [  9]],

         [[ 13],
          [ 17],
          [ 21]]],


        [[[ 25],
          [ 29],
          [ 33]],

         [[ 37],
          [ 41],
          [ 45]]],


        [[[ 49],
          [ 53],
          [ 57]],

         [[ 61],
          [ 65],
          [ 69]]]],



       [[[[ 73],
          [ 77],
          [ 81]],

         [[ 85],
          [ 89],
          [ 93]]],


        [[[ 97],
          [101],
          [105]],

         [[109],
          [113],
          [117]]],


        [[[121],
          [125],
          [129]],

         [[133],
          [137],
          [141]]]],



       [[[[145],
          [149],
          [153]],

         [[157],
          [161],
          [165]]],


        [[[169],
          [173],
          [177]],

         [[181],
          [185],
          [189]]],


        [[[193],
          [197],
          [201]],

         [[205],
          [209],
          [213]]]]])

In [60]:
A_7D_Array[...,1:2]

array([[[[[  1],
          [  5],
          [  9]],

         [[ 13],
          [ 17],
          [ 21]]],


        [[[ 25],
          [ 29],
          [ 33]],

         [[ 37],
          [ 41],
          [ 45]]],


        [[[ 49],
          [ 53],
          [ 57]],

         [[ 61],
          [ 65],
          [ 69]]]],



       [[[[ 73],
          [ 77],
          [ 81]],

         [[ 85],
          [ 89],
          [ 93]]],


        [[[ 97],
          [101],
          [105]],

         [[109],
          [113],
          [117]]],


        [[[121],
          [125],
          [129]],

         [[133],
          [137],
          [141]]]],



       [[[[145],
          [149],
          [153]],

         [[157],
          [161],
          [165]]],


        [[[169],
          [173],
          [177]],

         [[181],
          [185],
          [189]]],


        [[[193],
          [197],
          [201]],

         [[205],
          [209],
          [213]]]]])

# 12. Advanced Indexing

Unlike list in python, where we can access only one value, we can get multiple values. Advnaced indexing allows the access to variable arbitrarily, permitting them to be accessed out of order and even repeatedly.
<br>
the basix syntax of indexing is same. i.e
````python
Array[index]
````
but in case of advanced indexing, the index can be be iterable i.e. a NumPy Array, a tuple or a list of integer or bolean type. The result is a copy of array.

## 12a. integer indexing

in integer indexing, the index is an iterable of integers. so all values from NumPy Array whose index is present in index iterables are copied. for example, 
```` python
itrIndex = [p,q,..., y,z]
npArray[itrindex]

````

will return value from npArray at index p,q,...,y,z. <br>
Further can be ellaborated by examples below

###### let's start with 1-D NumPy array 

In [61]:
Adv_1D_indexing = np.arange(5, 15)
Adv_1D_indexing

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
# create a array which contains the indices
IndexArray = np.array([1,4,6,8])

In [63]:
SlicedUsingArray = Adv_1D_indexing[IndexArray]
SlicedUsingArray

array([ 6,  9, 11, 13])

``IndexArray`` contains ``[1,4,6,8] `` and ``Adv_1D_indexing[IndexArray]`` returns the values one indices specified in ``IndexArray`` which is ``[16, 9, 11, 13]`` and and all these values are return as an npArray

In [64]:
type(SlicedUsingArray)

numpy.ndarray

in above example, we created a array for indices, we can also acheive using list.

In [65]:
Adv_1D_indexing[[1,4,5,6]]

array([ 6,  9, 10, 11])

Now as we have seen advanced idexing of 1-D Array, we will now move to 2-D arrays.

###### with 2-D NumPy array:
in 2-D NumPy arrays, we can give two lists or array containing indices of our 2-D Array.
Consider following 2D Arrray


||        |||||
|:--------:|:------:|:------:|:------:|:------:|:------:|
|Column    |        |Column0 |Column1 |Column2 |Column3 |
|Index (j) |        |0       |1       |2       |3       | 
|row       |index(i)|        |        |        |        |
|row0      |0       |20      |21      |22      |23      |
|row1      |1       |24      |25      |26      |27      |
|row2      |2       |28      |29      |30      |31      |
|row3      |3       |32      |33      |34      |35      |
|row4      |4       |36      |37      |38      |39      |

In [66]:
AdvSlicing2DArray = np.arange(20,40).reshape(5,4)
AdvSlicing2DArray

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

``AdvSlicing2DArray[[2,4]]`` 
would return all columns of row2 and row4 of our 2D array, and resulting shape would be (2,4)

In [67]:
AdvSlicing2DArray[[2,4]]


array([[28, 29, 30, 31],
       [36, 37, 38, 39]])

``AdvSlicing2DArray[:,[1,3]]`` would return all rows of our column1 and column3, and resulting shape will be (5,2)

In [68]:
AdvSlicing2DArray[:,[1,3]]

array([[21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39]])

If required to get a specific values from 2-D array, It is bit trickeir, first we need to have an iterable that contains row indices of our required value, and second iterable need to be the indices of columns of these values.

For example, we need to extract ``21, 26, 31, 32, 37, 38``. Each of this value have following indices in terms of row, cloumn index pair are:

|Value|Index (rowIndex, ColumnIndex)|
|:---:|:---------------------------:|
|21   |(0, 1)                       |
|26   |(1, 2)                       |
|31   |(2, 3)                       |
|32   |(3, 0)                       |
|37   |(4, 1)                       |
|21   |(4, 2)                       |

<br>
Making Row and Column indices list from above pairs

In [69]:
rowIndices = [0,1,2,3,4,4]
colIndices = [1,2,3,0,1,2]

In [70]:
AdvSlicing2DArray[rowIndices, colIndices]

array([21, 26, 31, 32, 37, 38])

In this case we provided in terms of list and both list must be equal. Each list corresponds to each axis, i.e rows and columns of our 2-D array. 

###### with 3-D NumPy array:

Now we create a 3-D array with a shape of 2x5x4. 

||        ||*axis0*|axis0 index = 0||
|:--------:|:------:|:------:|:------:|:------:|:------:|
|          |axis2   |Column0 |Column1 |Column2 |Column3 |
|Index (j) |Index(j)|0       |1       |2       |3       | 
|axis1     |index(i)|        |        |        |        |
|row0      |0       |20      |21      |22      |23      |
|row1      |1       |24      |25      |26      |27      |
|row2      |2       |28      |29      |30      |31      |
|row3      |3       |32      |33      |34      |35      |
|row4      |4       |36      |37      |38      |39      |


||        ||*axis0*| axis0 index = 1||
|:--------:|:------:|:------:|:------:|:------:|:------:|
|          |axis2   |Column0 |Column1 |Column2 |Column3 |
|Index (j) |Index(j)|0       |1       |2       |3       | 
|axis1     |index(i)|        |        |        |        |
|row0      |0       |40      |41      |42      |43      |
|row1      |1       |44      |25      |26      |47      |
|row2      |2       |48      |49      |50      |51      |
|row3      |3       |52      |53      |54      |55      |
|row4      |4       |56      |57      |58      |59      |

In [71]:
AdvSlicing3DArray = np.arange(20,60).reshape(2,5,4)
AdvSlicing3DArray

array([[[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

Now we need to extarct ``29, 34, 48, 57`` from above 3-D array. In this case this values will have following, indices in terms of axis0, axis1(row), axis2(column)

|Value|Index (axi0,axis1,axis2)     |
|:---:|:---------------------------:|
|29   |(0, 2, 1)                    |
|34   |(0, 3, 2)                    |
|48   |(1, 2, 0)                    |
|32   |(1, 4, 1)                    |

Now in terms of lists:

In [72]:
axis0_Indices = [0, 0, 1, 1]
axis1_Indices = [2, 3, 2, 4]
axis2_Indices = [1, 2, 0, 1]

In [73]:
AdvSlicing3DArray[axis0_Indices, axis1_Indices, axis2_Indices]

array([29, 34, 48, 57])

## 12b. boolean indexing

This type of indexing uses boolean comparision to get the required element from an array. For example, if we have a NumPy array named ``npArray`` then 
```` python
npArray[npArray < Num]
````

will return all elements in ``npArray`` which are less than ``Num``.

In [74]:
BooleanIndexArr = np.random.randint(0,15,(3,4,5))

In [75]:
BooleanIndexArr

array([[[ 9,  2,  0,  4,  8],
        [ 6, 13,  6,  0, 14],
        [ 6,  2,  2,  2, 13],
        [ 4, 10,  1,  3, 11]],

       [[ 1,  8,  5,  2,  8],
        [ 5, 10, 13, 13,  6],
        [13,  5,  2,  4,  0],
        [12,  2,  3,  0,  1]],

       [[ 9,  0, 11, 14, 12],
        [ 2,  9,  9,  7, 14],
        [ 4, 10,  8,  6,  3],
        [13,  2, 12, 14,  0]]])

In [76]:
BooleanIndexArr[BooleanIndexArr < 5]

array([2, 0, 4, 0, 2, 2, 2, 4, 1, 3, 1, 2, 2, 4, 0, 2, 3, 0, 1, 0, 2, 4,
       3, 2, 0])

In [77]:
BooleanIndexArr[BooleanIndexArr > 5] # Should return all elements greater than 5

array([ 9,  8,  6, 13,  6, 14,  6, 13, 10, 11,  8,  8, 10, 13, 13,  6, 13,
       12,  9, 11, 14, 12,  9,  9,  7, 14, 10,  8,  6, 13, 12, 14])

In [78]:
BooleanIndexArr[BooleanIndexArr == 5] #should return all elements equal to five.

array([5, 5, 5])

# 13. Arithmetic operation with *NumPy Arrays*

Numpy arrays support two type of arithmetic operations:

1. Scalar Arithmetics.
2. Array Arithmetics.

## 13a. Scalar Arithmetics:

Scalar arithmetics is done while doing some operation with a single number. For example, if *npArray* is a array, ``npArray + 2`` will add 2 in each element of npArray. this is an example of scalar Arithmetics. 

In [79]:
npArray = np.random.randint(1,10,(2,3))

In [80]:
npArray

array([[9, 1, 2],
       [4, 3, 6]])

In [81]:
npArray + 2 

array([[11,  3,  4],
       [ 6,  5,  8]])

and Any mathmetical operation can be done.

In [82]:
npArray * 2

array([[18,  2,  4],
       [ 8,  6, 12]])

In [83]:
npArray - 5 

array([[ 4, -4, -3],
       [-1, -2,  1]])

In [84]:
npArray / 4

array([[2.25, 0.25, 0.5 ],
       [1.  , 0.75, 1.5 ]])

In [85]:
npArray ** 2

array([[81,  1,  4],
       [16,  9, 36]], dtype=int32)

## 13b. Array or Vector Arithmetics.

When arithmetics is done on two or more array, it is called array artihmetics. We will start wiht basic arithmetics operations such as add and sub on array with same dimensions and shapes
.

Consider two arrays

Array1 = [1,3,5,7]
and
Array2 = [0,2,4,8]
<br>
Array1 + Array2 will give an Array which will be [1, 5, 9, 15]. it adds the elements on same indices. In our example, the addition is done as below:<br>
``[0+1, 3+2, 5+4, 7+8] = [1, 5, 9, 15]``

In [86]:
Array1 = np.array([1,3,5,7])
Array2 = np.array([0,2,4,8])
Array1 + Array2

array([ 1,  5,  9, 15])

subtraction is done in the same way i.e. values at same indices are subtracted.

In [87]:
Array1 = np.array([1,3,5,7])
Array2 = np.array([0,2,4,6])
Array2 - Array1

array([-1, -1, -1, -1])

For two dimensial Arrays:

In [88]:
Array1 = np.random.randint(1,10,(2,3))
Array2 = np.random.randint(1,10,(2,3))
print("Array1", Array1, sep = "\n")
print("Array2", Array2, sep = "\n")


Array1
[[9 9 1]
 [7 7 1]]
Array2
[[7 1 1]
 [7 8 3]]


In [89]:
Array1 + Array2

array([[16, 10,  2],
       [14, 15,  4]])

similarly, elements on same index were added.
<br><br>
for multiplication, there are two type of multiplication.
1. Element wise multiplication (Scalar multiplication)
2. Matrix Multiplication

### 1. Element Wise multiplication:

In this type of multiplication, when multiplied each element of one array is element is multiple by element on same index on same array. For example:


In [90]:
Array1 = np.random.randint(1,10,(6,))
Array2 = np.random.randint(1,10,(6,))
print("Array1", Array1, sep = "\n")
print("Array2", Array2, sep = "\n")

Array1
[4 9 6 4 9 2]
Array2
[4 7 7 4 3 9]


In [91]:
Array1 * Array2

array([16, 63, 42, 16, 27, 18])

smilarly for multidimensional array: 

In [92]:
Array1 = np.random.randint(1,10,(2,2))
Array2 = np.random.randint(1,10,(2,2))
print("Array1", Array1, sep = "\n")
print("Array2", Array2, sep = "\n")

Array1
[[2 2]
 [2 5]]
Array2
[[5 8]
 [6 7]]


In [93]:
Array1 * Array2

array([[10, 16],
       [12, 35]])

### Matrix multiplication:

for Matrix multiplicaion, ``@`` operator is used. It has certain condition: for example. for 2D arrays with shapes (m,n) and (j,k); n must be equal to j. otherwise and error will be generated. and multiplication is done as follow:
<br>
Consider Matrix (arrray) a with a shape of (2, 3) 
<br>
$$ 
a = \begin{bmatrix} a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \end{bmatrix}
$$
<br> and another matrix b, with a shape of (3, 2)
$$
b = \begin{bmatrix} 
b_{00} & b_{01} \\ 
b_{10} & b_{11} \\
b_{20} & b_{21}\end{bmatrix}
$$
<br> as number of columns of a are eqrual to numner of rows of b, they can be multiplied. and the resultant matrix(array) will be

$$
res = \begin{bmatrix}  
a_{00} \times b_{00} + a_{01} \times b_{10} + a_{02} \times b_{20} & 
a_{00} \times b_{01} + a_{01} \times b_{11} + a_{02} \times b_{21} 
\\
a_{10} \times b_{00} + a_{11} \times b_{10} + a_{12} \times b_{20} & 
a_{10} \times b_{01} + a_{11} \times b_{11} + a_{12} \times b_{21}
\end{bmatrix}
$$

In [94]:
Array1 = np.array([[1,2,3],[4,5,6]])
Array1

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
Array2 = np.array([[1,2],[4,5],[7,8]])
Array2

array([[1, 2],
       [4, 5],
       [7, 8]])

For this Array1 and Array2, the matrix product is calculated as:

$$
\begin{bmatrix}  
1 \times 1 + 2 \times 4 + 3 \times 7 & 
1 \times 2 + 2 \times 5 + 3 \times 8 
\\
4 \times 1 + 6 \times 4 + 6 \times 7 & 
4 \times 2 + 5 \times 5 + 6 \times 8
\end{bmatrix}
$$

In [96]:
Array1 @ Array2

array([[30, 36],
       [66, 81]])

# 14. Broadcasting

The arithmetic operation between two arrays with different dimensions is done by using braodcasting. The simplest form of broadcasting is arithmetic operation with a scalar as we had seen earlier. For example, suppose one diemsional array. 

In [97]:
a = np.array([1,2,3,4,5])

Now suppose we add two in this array, the result is:


In [98]:
a + 2

array([3, 4, 5, 6, 7])

As it can be seen that 2 is added in each member of a it. What it seems to happens, not in actual, is 2 is *broadcasted* (stretched) over the length of array ``a`` and then both of these are added. A rough illustration can be as follow:

<img src = "npss\np1.PNG">

This was the simplest form of broadcasting. *But what if we want to have some arithmetic operation on two arrays?* In such case, we first need to check if *broadcasting* is possible by using *broadcasting rule*

### Broadcasting Rule:

The shape of two arrays are compared element wise from the trailing dimension (from right side), two dimensions are compatible if:

1. Both shape are equal.
2. Any of the shape is 1.

When all dimensions are compatible, broadcasting can be done otherwise an exception is thrown: ``ValueError: operands could not be broadcast together``.

In case broadcasting rule is satisified, the array is *broadcasted* over the missing dimensions and then arrithmetic operation is done.

Now let us see some examples, starting from simple and then going to the complex ones. Let us have two arrays, each of single dimension.

In [99]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,3,4])

In [100]:
array1.shape

(3,)

In [101]:
array2.shape

(4,)

let us add these two arrays:

In [102]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

an exception is thrown, it is because the ``array1`` shape is (3,) and ``array2`` shape is (4,) and clearly 3 and 4 not equal and therefor broadcasting cannot be done. Now let us take an example, of a 2 dimensional arrays. suppose an array:

In [103]:
array1 = np.arange(6).reshape(3,2)
array1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [104]:
array2 = np.arange(4).reshape(2,2)
array2

array([[0, 1],
       [2, 3]])

In [105]:
array1.shape

(3, 2)

In [106]:
array2.shape

(2, 2)

Now let's add these two arrays:

In [107]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

Now again we have an exception, but *why*?

``array1`` have a shape of (3, 2) and ``array2`` shape is (2, 2). Starting from the trailing dimensional(from right side) the shape of right most dimensions is 2 for both arrays. Now the next dimensions are to be compared, the shape of next dimension for ``array1`` is 3 and ``array2`` is 2. As neither the shape of this dimension is equal, nor any of the shape is 1, broadcasting is not possible.

Now let us assume two more arrays:


In [108]:
array1 = np.array([[1,2],[3, 4],[5,6]])
array1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
array2 = np.array([1, 2])
array2

array([1, 2])

In [110]:
array1.shape

(3, 2)

In [111]:
array2.shape

(2,)

Now let us add  both arrays

In [112]:
array1 + array2

array([[2, 4],
       [4, 6],
       [6, 8]])

Now ``array2`` is shape is (2) and and ``array1`` shape is (3, 2). Starting from right, both shapes are 2. Now because ``array2`` is single dimensional, no need to compare shape of next dimensions. Now as broadcasting is possible, ``array2`` is brodcasted over the missing dimension. And then both arrays are added. A rough depiction is:

<img src = "npss\np2.PNG">

let us have another example:
    

In [113]:
array1 = np.arange(48).reshape(2,3,4,2)
array1

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47]]]])

In [114]:
array2 = np.arange(8).reshape(1,4,2)
array2

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [115]:
array1.shape

(2, 3, 4, 2)

In [116]:
array2.shape

(1, 4, 2)

In [117]:
array1 + array2

array([[[[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14]],

        [[ 8, 10],
         [12, 14],
         [16, 18],
         [20, 22]],

        [[16, 18],
         [20, 22],
         [24, 26],
         [28, 30]]],


       [[[24, 26],
         [28, 30],
         [32, 34],
         [36, 38]],

        [[32, 34],
         [36, 38],
         [40, 42],
         [44, 46]],

        [[40, 42],
         [44, 46],
         [48, 50],
         [52, 54]]]])

 in this example, the shape of two dimensions from the right side are equal, but the shape of third dimension is not equal however the shape of ``array2`` for this dimension is 1. So now broadcasting can be done.

# 15. Array Manipulation.

This feature allows users to perform different operations. There are many mehtods used in array manipulation for different operation. Some of these are:


## 15a. Reshape
This method changes the shape of array without changing the data of array.

The exact signature of reshape method is:
```` python
np.reshape(a, newshape, order='C')
````

where:

**a** : is a numpy array.<br>
**Newshape**: new shape of array. should be a tuple.<br>
**order**(Optional): This specifies how the array is read for reshaping. It can have only three values {"C", "F", "A"}.<br>
*C* specifies a C-like array indexing for read/write, and "F" means Fortran-like indexing for read/write. 'A' means to read / write the elements in Fortran-like index order if ``a`` is Fortran *contiguous* in memory, C-like order otherwise.

In simple words. The *C* defines the element are populated row wise. While with "F", The elements are populated in columns wise. We will see that later with example.

for example 

```` python
LinearArray = np.arange(12)
LinearArray.shape
````

output will be a 1D array.
it contains 12 elements in single dimension. Say we need to change this into 2 dimensional array. we will use reshape function.


if we want to change the shape of this we will use rehape function.

```` python
ReshapedArray=LinearArray.reshape(2,6)
ReshapedArray.shape
````

Now the shape will be (2, 6)

In [125]:
np.reshape?

In [128]:
LinearArray = np.arange(12)
LinearArray.shape

(12,)

In [129]:
ReshapedArray=np.reshape(LinearArray, (2,6))
ReshapedArray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [130]:
ReshapedArray.shape

(2, 6)

As you is can be seen we haven't specified the third parameter and hence default "C" like order was used. and notice that now array is split into two half. The elements are first populated across the rows. 
<img src = "npss\np3.PNG">
Now let us see the output with Fortran-Like order.


In [131]:
np.reshape(LinearArray, (2,6),order = "F")

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

Now elements are first populated over the columns first.
<img src ="npss\np4.PNG">

### Other syntax for reshape:

Antoher syntax for reshape is as follow:

```` python
numpy.ndArray.reshape(NewShape)
````
It is in-place reshaping of an numpy array.

here the parameter newshape doesn't have to be a tuple, but simply a new shape. for Example:


In [132]:
LinearArray.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

##### Thing to take care:

While using reshape, it must be kept in mind that reshape doesn't alter data of array. so the new shape must be given such that all element must be fill all position on every index in new shape, in other words both must have a same size. For example, consider that we have an array with a shape of (2, 6), it will have 12 elements *(2x6)* if we rshape it into (2, 4) an exception is thro+wn because the new array could only have 8 elements, but actual elements are 12.

In [140]:
Array2By6 = np.random.randint(2, high = 10, size = (2, 6))
Array2By6

array([[4, 9, 6, 5, 7, 5],
       [6, 8, 2, 8, 6, 7]])

In [138]:
Array2By6.reshape(2, 4)

ValueError: cannot reshape array of size 12 into shape (2,4)

However, if I want to reshape is into (2,2,3) I would get no error as this shape have same size.


In [141]:
Array2By6.reshape(2,2,3)

array([[[4, 9, 6],
        [5, 7, 5]],

       [[6, 8, 2],
        [8, 6, 7]]])

## 15b. Resize

